NetCoreIdentityApp/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace NetCoreIdentityApp.Models
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; } = null!;
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; } = null!;
        public bool RememberMe { get; set; }
    }
}

NetCoreIdentityApp/Models/Register.cs
using System.ComponentModel.DataAnnotations;

namespace NetCoreIdentityApp.Models
{
    public class Register
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string? Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; } = null!;
        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and ConfirmPassword did not match")]
        public string? ConfirmPassword { get; set; }
    }
}

NetCoreIdentityApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace NetCoreIdentityApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NetCoreIdentityApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NetCoreIdentityApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

NetCoreIdentityApp/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NetCoreIdentityApp.Models;

namespace NetCoreIdentityApp.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        [BindProperty]
        public Login Model { get; set; } = null!;
        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAsync(string? returnUrl = null)
        {
            if(ModelState.IsValid)
            {
               var IdentityResult= await signInManager.PasswordSignInAsync(Model.Email, Model.Password, Model.RememberMe, false);
                if (IdentityResult.Succeeded)
                {
                    if(returnUrl == null || returnUrl == "/")
                    {
                        return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl);
                    }
                }
                ModelState.AddModelError("","UserName or Password Incorrect");
            }
            return Page();
        }
    }
}

NetCoreIdentityApp/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NetCoreIdentityApp.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;
        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }
        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

NetCoreIdentityApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NetCoreIdentityApp.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

NetCoreIdentityApp/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NetCoreIdentityApp.Models;

namespace NetCoreIdentityApp.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> singInManager;
        
        [BindProperty]
        public Register Model { get; set; } = null!;

        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.singInManager = signInManager;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if(ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = Model.Email,
                    Email=Model.Email
                };
                var result = await userManager.CreateAsync(user, Model.Password);
                if (result.Succeeded)
                {
                    //await singInManager.SignInAsync(user, false);
                    //return RedirectToPage("Index");
                    
                    _logger.LogInformation("User created a new account with password.");

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                    var callbackUrl = Url.Page(
                                    "/Account/ConfirmEmail",
                                    pageHandler: null,
                                    values: new { area = "Identity", userId = user.Id, code = code },
                                    protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(
                                    Input.Email, 
                                    "Confirm your email",
                                    $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                    if (_userManager.Options.SignIn.RequireConfirmedAccount)
                    {
                        return RedirectToPage("RegisterConfirmation", 
                                      new { email = Input.Email });
                    }
                    else
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        return LocalRedirect(returnUrl);
                    }
                }
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

            }

            return Page();
        }
    }
}

NetCoreIdentityApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetCoreIdentityApp/Pages/Login.cshtml
@page
@model NetCoreIdentityApp.Pages.LoginModel
@{
}
<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Email">Email Address</label>
                    <input type="text" asp-for="Model.Email" class="form-control" />
                    <span asp-asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password">Password</label>
                    <input type="password" asp-for="Model.Password" class="form-control" />
                    <span asp-asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <input type="checkbox" asp-for="Model.RememberMe" class="form-check-input" />
                    <label class="form-label" asp-for="Model.RememberMe">Remember Me?</label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

NetCoreIdentityApp/Pages/Logout.cshtml
@page
@model NetCoreIdentityApp.Pages.LogoutModel
@{
}
<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Are you sure want to  logout?</p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light m-lg-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

NetCoreIdentityApp/Pages/Register.cshtml
@page
@model NetCoreIdentityApp.Pages.RegisterModel
@{
}
<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Email">Email Address</label>
                    <input type="text" asp-for="Model.Email" class="form-control" />
                    <span asp-asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password">Password</label>
                    <input type="password" asp-for="Model.Password" class="form-control" />
                    <span asp-asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.ConfirmPassword">Confirm Password</label>
                    <input type="password" asp-for="Model.ConfirmPassword" class="form-control" />
                    <span asp-asp-validation-for="Model.ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>